# openapi2-functions.yaml
swagger: '2.0'
info:
  title: blogging-platform-365219
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
host: "echo-api.endpoints.blogging-platform-365219.cloud.goog"
schemes:
  - https
produces:
  - application/json
paths:
  /hello:
    get:
      summary: Greet a user
      operationId: hello
      x-google-backend:
        address: https://europe-west1-blogging-platform-365219.cloudfunctions.net/helloGET
      responses:
        '200':
          description: A successful response
          schema:
            type: string